# kubernetes/servicemonitor.yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: parson-test-one
  namespace: tools
  labels:
    release: monitoring                  # must match your Helm release name
spec:
  selector:
    matchLabels:
      app: parson-test-one  # label on your Service
  namespaceSelector:
    matchNames:
      - default   # your app namespace
  endpoints:
    - port: http                           # matches the Service port name
      path: /actuator/prometheus
      interval: 15s